<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Ekstrakulikuler_model extends CI_Model
{

    public $table = 'ekstrakulikuler';
    public $id = 'id_ekstra';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // datatables
    function json() {
        $this->datatables->select('id_ekstra,nama_ekstra,keterangan,image');
        $this->datatables->from('ekstrakulikuler');
        //add this line for join
        //$this->datatables->join('table2', 'ekstrakulikuler.field = table2.field');
        $this->datatables->add_column('action', anchor(site_url('ekstrakulikuler/read/$1'),'<i class="fa fa-eye" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
            ".anchor(site_url('ekstrakulikuler/update/$1'),'<i class="fa fa-pencil-square-o" aria-hidden="true"></i>', array('class' => 'btn btn-danger btn-sm'))." 
                ".anchor(site_url('ekstrakulikuler/delete/$1'),'<i class="fa fa-trash-o" aria-hidden="true"></i>','class="btn btn-danger btn-sm" onclick="javasciprt: return confirm(\'Are You Sure ?\')"'), 'id_ekstra');
        return $this->datatables->generate();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }
    function get_gambar($id){
        $this->db->where('id_ekstra',$id);
        return $this->db->get('ekstrakulikuler')->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('id_ekstra', $q);
	$this->db->or_like('nama_ekstra', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('image', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('id_ekstra', $q);
	$this->db->or_like('nama_ekstra', $q);
	$this->db->or_like('keterangan', $q);
	$this->db->or_like('image', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Ekstrakulikuler_model.php */
/* Location: ./application/models/Ekstrakulikuler_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2018-09-14 14:35:04 */
/* http://harviacode.com */